Repository OCA/openupgradelib, pull requests merged in 2021-02, with the labels that each got.

#226 [FIX] merge_records: complete _change_translations_sql method
  openupgradelib/openupgrade_merge_records.py
Labels: needs review

#229 [RVT] rename fields: revert deletion of existing ir_model_fields
  openupgradelib/openupgrade.py
Labels: bot is merging ⏳

#228 [IMP] add_fields: Be tolerant to existing fields
  openupgradelib/openupgrade.py
Labels: approved

#230 cow_templates_replicate_upstream: Run in end migration
  openupgradelib/openupgrade.py
Labels: bot is merging ⏳, enhancement
