Repository OCA/openupgradelib, pull requests merged in 2021-01, with the labels that each got.

#221 [FIX] add_xmlid: 14.0 compatibility
  openupgradelib/openupgrade.py
Labels: approved, bot is merging ⏳

#223 [FIX] add FROM
  openupgradelib/openupgrade.py
Labels: bot is merging ⏳, bug

#222 [FIX] Test invalid filters using a cursor savepoint
  openupgradelib/openupgrade.py
Labels: needs review

#224 [FIX] wrong operator
  openupgradelib/openupgrade.py
Labels: approved, bot is merging ⏳, bug
