Repository OCA/openupgradelib, pull requests merged in 2022-05, with the labels that each got.

#290 [IMP][15.0] openupgradelib: Since Odoo 15.0, Environment.manage() is useless
  openupgradelib/openupgrade.py
Labels: approved

#281 [ADD] update_module_moved_models
  openupgradelib/openupgrade.py
Labels: needs review, approved

#291 [FIX] update_module_moved_models: minor fix in a query
  openupgradelib/openupgrade.py
Labels: needs review

#292 [FIX] update_module_moved_models: fix queries
  openupgradelib/openupgrade.py
Labels: needs review
