Repository OCA/openupgradelib, pull requests merged in 2025-02, with the labels that each got.

#395 [IMP] rename_models: add condition to check version and existence of ir_property table
  openupgradelib/openupgrade.py
Labels: needs fixing, approved

#399 [IMP] ignore vscode folder
  .gitignore
Labels: approved

#400 [FIX] Deprecate setup_requires for pyproject.toml
  .travis.yml
  pyproject.toml
  requirements.txt
  setup.py
Labels: approved

#403 [FIX] rename_models: don't call get_model2table
  openupgradelib/openupgrade.py
Labels: needs review
