Repository OCA/openupgradelib, pull requests merged in 2025-03, with the labels that each got.

#405 [DEL] invalidate_cache: remove 'untested' warning
  openupgradelib/openupgrade_tools.py
Labels: approved, ready to merge

#402 [ADD] update_module_moved_translations
  openupgradelib/openupgrade.py
Labels: needs review, approved

#410 [FIX] openupgrade: fix module name retrieval
  openupgradelib/openupgrade.py
Labels: approved
