Repository OCA/openupgradelib, pull requests merged in 2025-04, with the labels that each got.

#413 [FIX] get_model2table: fill and track versions
  openupgradelib/openupgrade.py
Labels: needs review

#414 [IMP] rename_fields: rename ir_property names
  openupgradelib/openupgrade.py
Labels: needs review, approved

#412 [ADD] add_column: split from add_fields
  openupgradelib/openupgrade.py
Labels: needs review, approved

#415 [IMP] add_columns: Allow False as initialization value
  openupgradelib/openupgrade.py
Labels: approved

#417 [FIX] merge_records: norecompute was deprecated in v17
  openupgradelib/openupgrade_merge_records.py
Labels: needs review, approved
